import { useEffect, useRef, useState } from 'react';

type Feeling = 'racing' | 'tense' | 'scattered' | 'overwhelmed' | 'quiet' | 'unsure';
type Duration = '30 seconds' | '2 minutes' | '5 minutes' | 'No timer';
type Screen = 'welcome' | 'checkin' | 'duration' | 'recommendation' | 'practice' | 'complete' | 'library' | 'journal' | 'settings' | 'support';
type Modality = 'Grounding' | 'Body' | 'Breathing' | 'Journal' | 'Quiet visual';
type Practice = { id: string; title: string; modality: Modality; duration: string; intro: string; steps: string[]; alternativeId?: string };

const feelings: Array<{ id: Feeling; label: string }> = [
  { id: 'racing', label: 'My thoughts are racing' }, { id: 'tense', label: 'My body feels tense' }, { id: 'scattered', label: 'I feel scattered or disconnected' }, { id: 'overwhelmed', label: 'Everything feels like too much' }, { id: 'quiet', label: 'I just want some quiet' }, { id: 'unsure', label: 'I’m not sure' },
];
const practices: Practice[] = [
  { id: 'three-things', title: 'Name three things', modality: 'Grounding', duration: '30 seconds', intro: 'A brief way to orient to what is around you.', steps: ['Notice one thing you can see. It can be ordinary.', 'If it feels comfortable, notice one point of support — a floor, seat, wall or bed.', 'Name one sound you can hear. If there is no sound, notice one more visible detail instead.', 'Nothing needs to be solved in this moment. You can stop whenever you want.'] },
  { id: 'feet', title: 'Feel your feet', modality: 'Grounding', duration: '30 seconds', intro: 'A small invitation to notice support.', steps: ['Let your attention rest on where your feet are, if that feels comfortable.', 'Notice pressure, temperature or texture — or simply look at an object nearby.', 'Choose one detail to stay with for another moment.', 'You can carry on from here, or choose something else.'] },
  { id: 'release', title: 'Release three places', modality: 'Body', duration: '2 minutes', intro: 'A gentle noticing practice. No movement is required.', steps: ['Notice your jaw, without needing to change it.', 'Notice your shoulders. They can stay exactly as they are.', 'Notice your hands, or another part of you that feels neutral.', 'If any area feels like too much, leave it alone and look around the room instead.'] },
  { id: 'five-fingers', title: 'Five-finger breathing', modality: 'Breathing', duration: '2 minutes', intro: 'Place one hand open, if that feels comfortable. Use one finger from your other hand to slowly trace along it.', steps: ['Start at the base of your thumb. Trace gently up its side as you take an easy breath in — or simply trace without changing your breathing.', 'Trace down the other side as you breathe out in your own time.', 'Continue up and down each finger at any pace that feels comfortable. There is no need to finish all five.', 'If breathing or hand movement does not feel right, pause and name three things you can see instead.'], alternativeId: 'three-things' },
  { id: 'breathing', title: 'Gentle equal breathing', modality: 'Breathing', duration: '2 minutes', intro: 'Only if breathing feels comfortable. Follow your own pace; there is nothing to match.', steps: ['Let your breathing be natural for a moment.', 'If it feels comfortable, notice one easy inhale and one easy exhale.', 'You might let the next exhale be unhurried. No counting is needed.', 'If this is not helpful, switch to grounding. You are not doing anything wrong.'], alternativeId: 'three-things' },
  { id: 'colour', title: 'Find a colour', modality: 'Grounding', duration: '2 minutes', intro: 'A quiet visual orientation with no right way to do it.', steps: ['Choose a colour you can see.', 'Find one object with that colour.', 'Find another, and notice one small difference between them.', 'If looking around is not right for this moment, name three neutral things you remember instead.'] },
  { id: 'body-scan', title: 'Short body scan', modality: 'Body', duration: '5 minutes', intro: 'A flexible scan. Your eyes can stay open and you can skip any area.', steps: ['Notice a place that feels supported. You do not need to move.', 'Bring attention to your lower body only if that feels okay; otherwise, notice the room.', 'Let attention move to your middle or hands, and skip anything you would rather not notice.', 'Notice your face or a neutral point in the room.', 'Take the next step that feels kindest: continue, stop, or choose another practice.'] },
  { id: 'unload', title: 'Thought-unloading prompt', modality: 'Journal', duration: '5 minutes', intro: 'A private prompt you can answer later in your journal.', steps: ['What feels most demanding right now?', 'What can wait until later?', 'What is one small thing you need?', 'Your answer does not need to be neat, useful or complete.'] },
  { id: 'visual', title: 'Still-point pause', modality: 'Quiet visual', duration: 'No timer', intro: 'A text-led pause with no timer and no movement to follow.', steps: ['Look at one steady point, or rest your eyes somewhere comfortable.', 'Notice one colour, texture or edge.', 'There is nowhere else you need to be for this moment.', 'Stay as long as you like, or choose your next small step.'] },
  { id: 'reset', title: 'General reset', modality: 'Grounding', duration: '2 minutes', intro: 'A simple orientation when you are not sure what you need.', steps: ['Notice one thing that feels steady or familiar.', 'Notice one point of support, or one neutral object.', 'Ask: what would make the next ten minutes slightly easier?', 'You do not have to act on the answer right now.'] },
];
const matrix: Record<Feeling, Record<Duration, string>> = {
  racing: { '30 seconds': 'three-things', '2 minutes': 'colour', '5 minutes': 'unload', 'No timer': 'unload' }, tense: { '30 seconds': 'feet', '2 minutes': 'release', '5 minutes': 'body-scan', 'No timer': 'body-scan' }, scattered: { '30 seconds': 'feet', '2 minutes': 'three-things', '5 minutes': 'colour', 'No timer': 'colour' }, overwhelmed: { '30 seconds': 'three-things', '2 minutes': 'five-fingers', '5 minutes': 'unload', 'No timer': 'three-things' }, quiet: { '30 seconds': 'visual', '2 minutes': 'visual', '5 minutes': 'visual', 'No timer': 'visual' }, unsure: { '30 seconds': 'three-things', '2 minutes': 'reset', '5 minutes': 'unload', 'No timer': 'visual' },
};
const byId = (id: string) => practices.find((practice) => practice.id === id)!;
const sessionFor = (feeling: Feeling, duration: Duration) => {
  const first = byId(matrix[feeling][duration]);
  if (duration === '30 seconds') return [first];
  const extras: Record<Feeling, string[]> = { racing: ['three-things', 'feet'], tense: ['feet', 'colour'], scattered: ['release', 'colour'], overwhelmed: ['three-things', 'unload'], quiet: ['visual', 'colour'], unsure: ['three-things', 'unload'] };
  const count = duration === '2 minutes' ? 1 : 2;
  return [first, ...extras[feeling].slice(0, count).map(byId)];
};

export function App() {
  const [screen, setScreen] = useState<Screen>('welcome'); const [feeling, setFeeling] = useState<Feeling | null>(null); const [duration, setDuration] = useState<Duration | null>(null); const [session, setSession] = useState<Practice[]>([practices[0]]); const [sessionIndex, setSessionIndex] = useState(0); const [selectedPractice, setSelectedPractice] = useState<Practice>(practices[0]); const [step, setStep] = useState(0);
  const goToday = () => { setFeeling(null); setDuration(null); setStep(0); setScreen('checkin'); };
  const choosePractice = (practice: Practice) => { setSession([practice]); setSessionIndex(0); setSelectedPractice(practice); setStep(0); setScreen('recommendation'); };
  const selectDuration = (value: Duration) => { const nextSession = sessionFor(feeling ?? 'unsure', value); setDuration(value); setSession(nextSession); setSessionIndex(0); setSelectedPractice(nextSession[0]); setStep(0); setScreen('recommendation'); };
  const advance = () => { if (step < selectedPractice.steps.length - 1) { setStep(step + 1); return; } if (sessionIndex < session.length - 1) { const next = session[sessionIndex + 1]; setSessionIndex(sessionIndex + 1); setSelectedPractice(next); setStep(0); return; } setScreen('complete'); };
  return <main className="app-shell"><header className="topbar"><button className="brand" onClick={() => setScreen('welcome')} aria-label="Return to Unwind home">Unwind<span>·</span></button><button className="quiet-link" onClick={() => setScreen('support')}>Need support?</button></header><section className="content" aria-live="polite">
    {screen === 'welcome' && <Welcome onBegin={goToday} />}{screen === 'checkin' && <CheckIn onSelect={(value) => { setFeeling(value); setScreen('duration'); }} />}{screen === 'duration' && <DurationPick onSelect={selectDuration} onBack={goToday} />}{screen === 'recommendation' && <Recommendation practice={selectedPractice} duration={duration} sessionCount={session.length} onStart={() => setScreen('practice')} onChooseAgain={() => setScreen('library')} onNotNow={() => setScreen('welcome')} />}{screen === 'practice' && <PracticePlayer practice={selectedPractice} step={step} hasAnotherPractice={sessionIndex < session.length - 1} onNext={advance} onStop={goToday} onAlternative={() => selectedPractice.alternativeId && choosePractice(byId(selectedPractice.alternativeId))} />}{screen === 'complete' && <Complete practice={selectedPractice} onAgain={() => setScreen('library')} onJournal={() => setScreen('journal')} />}{screen === 'library' && <Library onSelect={choosePractice} />}{screen === 'journal' && <Placeholder label="Journal" title="A private place for your words." text="The local journal is the next feature being built. Entries will stay in this browser on this device." />}{screen === 'settings' && <Placeholder label="Settings" title="Make this space your own." text="Motion, privacy and local-data controls are being added next." />}{screen === 'support' && <Support onBack={() => setScreen('welcome')} />}
  </section><nav className="bottom-nav" aria-label="Primary navigation"><button className={['checkin','duration','recommendation','practice','complete'].includes(screen) ? 'active' : ''} onClick={goToday}>Today</button><button className={screen === 'library' ? 'active' : ''} onClick={() => setScreen('library')}>Practices</button></nav></main>;
}
function Welcome({ onBegin }: { onBegin: () => void }) { return <div className="hero"><p className="eyebrow">A quiet place to begin</p><h1>A little space when everything feels like a lot.</h1><p className="lead">Small, private wellbeing exercises. Nothing needs to be fixed right now.</p><button className="primary" onClick={onBegin}>Begin</button><p className="fineprint">Unwind is for general wellbeing, not medical care, therapy or crisis support.</p></div>; }
function CheckIn({ onSelect }: { onSelect: (value: Feeling) => void }) { return <div className="panel"><p className="eyebrow">Today</p><h1>What feels closest right now?</h1><p className="lead">Choose the nearest fit. You do not need to get it exactly right.</p><div className="choice-list">{feelings.map((item) => <button key={item.id} className="choice" onClick={() => onSelect(item.id)}>{item.label}<span aria-hidden="true">→</span></button>)}</div></div>; }
function DurationPick({ onSelect, onBack }: { onSelect: (value: Duration) => void; onBack: () => void }) { return <div className="panel"><button className="back" onClick={onBack}>← Back</button><p className="eyebrow">One small step</p><h1>How much time feels manageable?</h1><div className="duration-grid">{(['30 seconds','2 minutes','5 minutes','No timer'] as Duration[]).map((item) => <button className="duration" key={item} onClick={() => onSelect(item)}>{item}</button>)}</div></div>; }
function Recommendation({ practice, duration, sessionCount, onStart, onChooseAgain, onNotNow }: { practice: Practice; duration: Duration | null; sessionCount: number; onStart: () => void; onChooseAgain: () => void; onNotNow: () => void }) { return <div className="panel recommendation"><p className="eyebrow">A gentle suggestion</p><h1>{practice.title}</h1><p className="lead">{practice.intro}{duration ? ` Chosen for ${duration.toLowerCase()}.` : ''}</p><div className="soft-card"><p>{practice.modality}</p><strong>{practice.duration}</strong><span>{sessionCount === 1 ? 'One small practice' : `${sessionCount} small practices, one at a time`}</span></div><button className="primary" onClick={onStart}>Start</button><button className="secondary" onClick={onChooseAgain}>Choose something else</button><button className="text-button" onClick={onNotNow}>Not now</button></div>; }
function PracticePlayer({ practice, step, hasAnotherPractice, onNext, onStop, onAlternative }: { practice: Practice; step: number; hasAnotherPractice: boolean; onNext: () => void; onStop: () => void; onAlternative: () => void }) { return <div className="practice"><div className="progress-label"><span>{practice.modality} · step {step + 1} of {practice.steps.length}</span><button onClick={onStop}>Stop</button></div>{practice.id === 'five-fingers' && <div className="finger-guide" aria-label="Five fingers to trace, one at a time"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><p>Trace up one finger, then down. Follow your own natural breath, or simply trace.</p></div>}<div className="practice-card"><p className="eyebrow">{practice.title}</p><h1>{practice.steps[step]}</h1><p className="lead">If this does not feel helpful, you can skip it or choose something else.</p><ListenControls text={practice.steps[step]} /></div><div className="transcript"><p>Full practice text</p><ol>{practice.steps.map((script, index) => <li key={script} className={index === step ? 'current' : ''}>{script}</li>)}</ol></div><button className="primary" onClick={onNext}>{step === practice.steps.length - 1 ? (hasAnotherPractice ? 'Next small practice' : 'Finish') : 'Next small notice'}</button><button className="secondary" onClick={onNext}>Skip this one</button>{practice.alternativeId && <button className="text-button" onClick={onAlternative}>Breathing feels uncomfortable — try grounding</button>}</div>; }
function ListenControls({ text }: { text: string }) { const [rate, setRate] = useState(0.85); const [speaking, setSpeaking] = useState(false); const utterance = useRef<SpeechSynthesisUtterance | null>(null); useEffect(() => () => window.speechSynthesis?.cancel(), []); const stop = () => { window.speechSynthesis?.cancel(); setSpeaking(false); }; const listen = () => { if (!('speechSynthesis' in window)) return; stop(); const next = new SpeechSynthesisUtterance(text); utterance.current = next; next.rate = rate; next.pitch = 1; next.onend = () => setSpeaking(false); next.onerror = () => setSpeaking(false); window.speechSynthesis.speak(next); setSpeaking(true); }; if (!('speechSynthesis' in window)) return <p className="voice-note">Listening is not available in this browser. The full written practice is above.</p>; return <div className="listen-controls"><label>Listening speed<select value={rate} onChange={(event) => setRate(Number(event.target.value))}><option value={0.85}>Gentle</option><option value={1}>Standard</option></select></label><button className="listen" onClick={listen}>Listen to this step</button>{speaking && <button className="stop-listening" onClick={stop}>Stop listening</button>}<p>Uses your device’s available voice. It never starts on its own.</p></div>; }
function Complete({ practice, onAgain, onJournal }: { practice: Practice; onAgain: () => void; onJournal: () => void }) { return <div className="hero"><p className="eyebrow">You’re here</p><h1>You made a little space for yourself.</h1><p className="lead">You completed {practice.title.toLowerCase()}. You can carry on or choose a different small step.</p><button className="primary" onClick={onAgain}>Try something different</button><button className="secondary" onClick={onJournal}>Write something down</button></div>; }
function Library({ onSelect }: { onSelect: (practice: Practice) => void }) { return <div className="panel"><p className="eyebrow">Practices</p><h1>Choose what feels doable.</h1><p className="lead">Each practice is optional, text-led and easy to leave.</p><div className="choice-list">{practices.map((practice) => <button className="choice" key={practice.id} onClick={() => onSelect(practice)}><span><strong>{practice.title}</strong><small>{practice.modality} · {practice.duration}</small></span><span aria-hidden="true">→</span></button>)}</div></div>; }
function Placeholder({ label, title, text }: { label: string; title: string; text: string }) { return <div className="panel"><p className="eyebrow">{label}</p><h1>{title}</h1><p className="lead">{text}</p></div>; }
function Support({ onBack }: { onBack: () => void }) { return <div className="panel"><button className="back" onClick={onBack}>← Back</button><p className="eyebrow">Need support?</p><h1>You do not have to carry it alone.</h1><p className="lead">Unwind is not crisis support. In Australia, call Triple Zero (000) for immediate danger, Lifeline on 13 11 14, or Beyond Blue on 1300 22 4636.</p><button className="primary" onClick={onBack}>Return to Unwind</button></div>; }
